ECHO OFF
ECHO LINTING ...
call npm run lint

ECHO GULP task ...
call npm run gulp -- ci_build_transform

ECHO UNIT testing ...
call npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI

ECHO E2E testing ...
call npm run e2e -- --configuration=ci

ECHO Push source code to Salesforce ...
call npm run sfdx -- force:source:push --targetusername=my-dev-scratch

ECHO Apex Unit testing on Salesforce ...
call npm run sfdx -- force:apex:test:run --targetusername=my-dev-scratch --codecoverage --resultformat junit --outputdir ./coverage/force --wait 10
